<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Earnings Report - PisoNet Central</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            font-size: 12px;
            color: #333;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 2px solid #00c8ff;
        }
        .header h1 {
            font-size: 24px;
            color: #040c18;
            margin-bottom: 5px;
        }
        .header p {
            font-size: 12px;
            color: #666;
        }
        .info-row {
            display: flex;
            justify-content: space-between;
            margin-bottom: 20px;
        }
        .info-box {
            background: #f8f9fa;
            padding: 15px;
            border-radius: 8px;
            flex: 1;
            margin-right: 10px;
        }
        .info-box:last-child {
            margin-right: 0;
        }
        .info-box label {
            display: block;
            font-size: 10px;
            color: #666;
            text-transform: uppercase;
            margin-bottom: 5px;
        }
        .info-box .value {
            font-size: 18px;
            font-weight: bold;
            color: #040c18;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background: #040c18;
            color: #fff;
            padding: 12px 8px;
            text-align: left;
            font-size: 10px;
            text-transform: uppercase;
        }
        td {
            padding: 10px 8px;
            border-bottom: 1px solid #eee;
        }
        tr:nth-child(even) {
            background: #f8f9fa;
        }
        .amount {
            font-weight: bold;
            color: #00a854;
        }
        .status {
            padding: 3px 8px;
            border-radius: 4px;
            font-size: 10px;
            font-weight: bold;
        }
        .status-completed {
            background: #d9f7be;
            color: #389e0d;
        }
        .status-pending {
            background: #fff7e6;
            color: #fa8c16;
        }
        .status-refunded {
            background: #ffccc7;
            color: #cf1322;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #999;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>PisoNet Central</h1>
        <p>Earnings Report - {{ ucfirst($filter) }}</p>
    </div>

    <div class="info-row">
        <div class="info-box">
            <label>Total Earnings</label>
            <div class="value">₱{{ number_format($totalAmount, 2) }}</div>
        </div>
        <div class="info-box">
            <label>Total Transactions</label>
            <div class="value">{{ $earnings->count() }}</div>
        </div>
        <div class="info-box">
            <label>Generated At</label>
            <div class="value" style="font-size: 14px;">{{ $generatedAt }}</div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Transaction ID</th>
                <th>Terminal</th>
                <th>Type</th>
                <th>Date & Time</th>
                <th>Amount</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($earnings as $earning)
            <tr>
                <td>{{ $earning->transaction_id }}</td>
                <td>{{ $earning->terminal }}</td>
                <td>{{ ucfirst($earning->type) }}</td>
                <td>{{ $earning->date_and_time->format('M d, Y H:i:s') }}</td>
                <td class="amount">₱{{ number_format($earning->amount, 2) }}</td>
                <td>
                    <span class="status status-{{ $earning->status }}">
                        {{ ucfirst($earning->status) }}
                    </span>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This report was automatically generated by PisoNet Central System</p>
    </div>
</body>
</html>

